export type Permission = 'admin' | 'manager' | 'all';

export interface Command {
  id: string;
  name: string;
  command: string;
  description: string;
  permission: Permission;
  example?: string;
  warning?: string;
  related?: string[];
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  description: string;
  commands: Command[];
}

export const categories: Category[] = [
  {
    id: 'member',
    name: '管理成员',
    icon: '👤',
    description: '成员权限、踢人、黑名单管理',
    commands: [
      {
        id: 'set-admin',
        name: '设置管理员',
        command: '@XXX 666',
        description: '设置当前群管理员权限',
        permission: 'admin',
        warning: '有数量限制',
      },
      {
        id: 'remove-admin',
        name: '取消管理员',
        command: '@XXX 555',
        description: '取消当前群管理员权限',
        permission: 'admin',
      },
      {
        id: 'kick',
        name: '踢出群聊',
        command: '@XXX 78',
        description: '将某人踢出群',
        permission: 'manager',
      },
      {
        id: 'ban',
        name: '永久踢出',
        command: '@XXX 4444',
        description: '将某人踢出群，进群再次自动踢出去',
        permission: 'admin',
        warning: '查看永久黑名单可解除',
      },
      {
        id: 'blacklist',
        name: '加入小黑屋',
        command: '@XXX 444',
        description: 'AI助手不再回复XXX某人指令',
        permission: 'manager',
        related: ['view-blacklist'],
      },
      {
        id: 'unblacklist',
        name: '移出小黑屋',
        command: '@XXX 333',
        description: 'AI助手再次应答XXX某人指令',
        permission: 'manager',
        example: '移出小黑屋#wxid',
      },
      {
        id: 'view-admin',
        name: '查看管理',
        command: '查管理',
        description: '查看本群超管和普通管理',
        permission: 'admin',
      },
      {
        id: 'view-blacklist',
        name: '小黑屋',
        command: '小黑屋',
        description: '查看禁用功能的用户',
        permission: 'admin',
        example: '移除黑名单：@某人 333',
      },
      {
        id: 'view-blacklist-alt',
        name: '查看黑名单',
        command: '查看黑名单',
        description: '查看禁用功能的用户',
        permission: 'admin',
        example: '移除黑名单：@某人 333',
      },
      {
        id: 'view-permanent-blacklist',
        name: '查看永久黑名单',
        command: '查看永久黑名单',
        description: '查看禁止进群用户名单',
        permission: 'admin',
        example: '解除：解除永久黑名单#wxid',
      },
      {
        id: 'clear-admin',
        name: '清空管理员',
        command: '清空管理员',
        description: '清空本群普通管理',
        permission: 'admin',
      },
      {
        id: 'clear-blacklist',
        name: '清空黑名单',
        command: '清空黑名单',
        description: '清空本群小黑屋（禁用功能）用户',
        permission: 'admin',
      },
    ],
  },
  {
    id: 'currency',
    name: '管理金币魅力',
    icon: '💰',
    description: '金币、积分、魅力、身价的增减和清零',
    commands: [
      {
        id: 'add-coins',
        name: '加金币',
        command: '@XXX 加金币#10',
        description: '给XXX增加10金币',
        permission: 'manager',
        warning: '加多变负数，慎重',
        example: '@XXX 加金币#数字',
      },
      {
        id: 'add-points',
        name: '加积分',
        command: '@XXX 加积分#10',
        description: '给XXX增加10积分',
        permission: 'manager',
        warning: '加多变负数，慎重',
      },
      {
        id: 'add-charm',
        name: '加魅力',
        command: '@XXX 加魅力#10',
        description: '给XXX增加10魅力',
        permission: 'admin',
        warning: '加多变负数，慎重',
      },
      {
        id: 'batch-add-charm',
        name: '批量加魅力',
        command: '批量加魅力#10',
        description: '给所有签到过用户加10魅力',
        permission: 'admin',
      },
      {
        id: 'batch-add-coins',
        name: '批量加金币',
        command: '批量加金币#10',
        description: '给所有签到过用户加10金币',
        permission: 'admin',
      },
      {
        id: 'batch-add-points',
        name: '批量加积分',
        command: '批量加积分#10',
        description: '给所有签到过用户加10积分',
        permission: 'admin',
      },
      {
        id: 'batch-add-worth',
        name: '批量加身价',
        command: '批量加身价#10',
        description: '给所有签到过用户加10身价',
        permission: 'admin',
      },
      {
        id: 'clear-points',
        name: '清空积分',
        command: '清空积分',
        description: '清空本群所有用户积分',
        permission: 'admin',
      },
      {
        id: 'clear-coins',
        name: '清空金币',
        command: '清空金币',
        description: '清空本群所有用户金币',
        permission: 'admin',
      },
      {
        id: 'clear-charm',
        name: '清空魅力',
        command: '清空魅力',
        description: '清空本群所有用户魅力',
        permission: 'admin',
      },
      {
        id: 'clear-marriage',
        name: '清空结婚',
        command: '清空结婚',
        description: '清空本群所有用户结婚数据',
        permission: 'admin',
      },
      {
        id: 'clear-slave',
        name: '清空奴隶',
        command: '清空奴隶',
        description: '清空本群所有用户奴隶数据',
        permission: 'admin',
      },
      {
        id: 'clear-checkin',
        name: '清空签到',
        command: '清空签到',
        description: '清空本群所有用户签到数据',
        permission: 'admin',
      },
      {
        id: 'clear-rob',
        name: '清空打劫',
        command: '清空打劫',
        description: '清空本群所有用户打劫数据',
        permission: 'admin',
      },
      {
        id: 'reset-user-coins',
        name: '金币清零',
        command: '@XXX 金币清零',
        description: '把XXX金币归零',
        permission: 'admin',
      },
      {
        id: 'reset-user-points',
        name: '积分清零',
        command: '@XXX 积分清零',
        description: '把XXX积分归零',
        permission: 'admin',
      },
      {
        id: 'reset-user-worth',
        name: '身价清零',
        command: '@XXX 身价清零',
        description: '把XXX身价归零',
        permission: 'admin',
      },
      {
        id: 'reset-user-charm',
        name: '魅力清零',
        command: '@XXX 魅力清零',
        description: '把XXX魅力归零',
        permission: 'admin',
      },
      {
        id: 'clear-marriage-props',
        name: '清空结婚道具',
        command: '@XXX 清空结婚道具',
        description: '把XXX结婚道具效果复位',
        permission: 'admin',
      },
      {
        id: 'force-divorce',
        name: '仲裁离婚',
        command: '@XXX 仲裁离婚',
        description: '棒打鸳鸯',
        permission: 'admin',
      },
      {
        id: 'my-messages',
        name: '我的发言',
        command: '我的发言',
        description: '查询本人群内发言详情',
        permission: 'all',
      },
      {
        id: 'my-invites',
        name: '我的邀请',
        command: '我的邀请',
        description: '查询本人邀请用户进群数量',
        permission: 'all',
      },
      {
        id: 'my-coins',
        name: '我的金币',
        command: '我的金币',
        description: '查询本人金币，积分，魅力，身价详情',
        permission: 'all',
      },
    ],
  },
  {
    id: 'ranking',
    name: '查看排行榜',
    icon: '📊',
    description: '各种活跃度和属性排行榜',
    commands: [
      {
        id: 'rank-daily-active',
        name: '日活跃榜',
        command: '日活跃榜',
        description: '当天群内发言统计排行',
        permission: 'admin',
      },
      {
        id: 'rank-monthly-active',
        name: '月活跃榜',
        command: '月活跃榜',
        description: '当月群内发言统计排行',
        permission: 'admin',
      },
      {
        id: 'rank-total-active',
        name: '总活跃榜',
        command: '总活跃榜',
        description: '群内所有发言统计排行',
        permission: 'admin',
      },
      {
        id: 'rank-lurkers',
        name: '潜水统计',
        command: '潜水统计',
        description: '统计群内长期未发言用户',
        permission: 'admin',
      },
      {
        id: 'rank-daily-lurkers',
        name: '当日潜水统计',
        command: '当日潜水统计',
        description: '统计当天群内未发言用户',
        permission: 'admin',
      },
      {
        id: 'rank-invites',
        name: '邀请排行榜',
        command: '邀请排行榜',
        description: '邀请排行',
        permission: 'admin',
      },
      {
        id: 'rank-coins',
        name: '金币排行榜',
        command: '金币排行榜',
        description: '金币排行，当天签到才会上榜',
        permission: 'all',
      },
      {
        id: 'rank-points',
        name: '积分排行榜',
        command: '积分排行榜',
        description: '积分排行，当天签到才会上榜',
        permission: 'all',
      },
      {
        id: 'rank-charm',
        name: '魅力排行榜',
        command: '魅力排行榜',
        description: '魅力排行，当天签到才会上榜',
        permission: 'all',
      },
      {
        id: 'rank-worth',
        name: '身价排行榜',
        command: '身价排行榜',
        description: '身价排行，当天签到才会上榜',
        permission: 'all',
      },
      {
        id: 'rank-total-checkin',
        name: '累计签到排行榜',
        command: '累计签到排行榜',
        description: '累计签到排行，当天签到才会上榜',
        permission: 'all',
      },
      {
        id: 'rank-streak-checkin',
        name: '连续签到排行榜',
        command: '连续签到排行榜',
        description: '连续签到排行，当天签到才会上榜',
        permission: 'all',
      },
    ],
  },
  {
    id: 'features',
    name: '功能开关',
    icon: '🎮',
    description: '开启或关闭群功能',
    commands: [
      {
        id: 'enable-all',
        name: '开启功能',
        command: '开启功能',
        description: '启用以下所有功能，不包含入群欢迎',
        permission: 'admin',
        related: [
          'point-song',
          'sign-board',
          'signature',
          'movie',
          'find-diff',
          'rob',
          'gift',
          'checkin',
          'points',
          'slave',
          'marriage',
          'force-marriage',
          'steal-marriage',
          'guess-song',
          'guess-number',
          'guess-idiom',
          'guess-car',
          'guess-hero',
          'one-stop',
          'super-dict',
          'idiom-chain',
          'ai-reply',
        ],
      },
      {
        id: 'disable-all',
        name: '关闭功能',
        command: '关闭功能',
        description: '禁用当前群的AI助手，会关闭入群欢迎',
        permission: 'admin',
      },
      {
        id: 'disable-all-1',
        name: '关闭功能1',
        command: '关闭功能1',
        description: '禁用当前群的AI助手，保留入群欢迎',
        permission: 'admin',
      },
      {
        id: 'disable-all-2',
        name: '关闭功能2',
        command: '关闭功能2',
        description: '禁用当前群的AI助手，保留入群欢迎和监控',
        permission: 'admin',
      },
      {
        id: 'enable-welcome',
        name: '开启入群欢迎',
        command: '开启入群欢迎',
        description: '用户进群欢迎文字提示，包含语音和卡片头像',
        permission: 'admin',
      },
      {
        id: 'disable-welcome-voice',
        name: '关闭入群语音',
        command: '关闭入群语音',
        description: '关闭用户入群时语音提示',
        permission: 'admin',
      },
      {
        id: 'disable-welcome-avatar',
        name: '关闭入群头像',
        command: '关闭入群头像',
        description: '关闭用户入群时卡片头像提示',
        permission: 'admin',
      },
      {
        id: 'set-welcome',
        name: '欢迎语设置',
        command: '欢迎语#XXX',
        description: '设置入群欢迎内容为XXX',
        permission: 'admin',
        example: '没有反应的回复：开启入群欢迎',
      },
    ],
  },
  {
    id: 'system',
    name: '系统查询',
    icon: '⚙️',
    description: '系统信息和群设置查询',
    commands: [
      {
        id: 'validity',
        name: '有效期',
        command: '有效期',
        description: '查看当前群到期时间',
        permission: 'admin',
      },
      {
        id: 'group-report',
        name: '群报告',
        command: '群报告',
        description: '刷新本地群成员昵称数据',
        permission: 'admin',
      },
      {
        id: 'activate',
        name: '开通群',
        command: '开通#XXXXX',
        description: '利用激活码激活本群，激活人员自动成为本群超管',
        permission: 'admin',
      },
    ],
  },
];

// 功能列表（用于功能开关）
export const features = [
  { id: 'point-song', name: '点歌', icon: '🎵' },
  { id: 'sign-board', name: '举牌', icon: '📸' },
  { id: 'signature', name: '签名', icon: '✍️' },
  { id: 'movie', name: '电影', icon: '🎬' },
  { id: 'find-diff', name: '找茬', icon: '🔍' },
  { id: 'rob', name: '打劫', icon: '💰' },
  { id: 'gift', name: '礼物', icon: '🎁' },
  { id: 'checkin', name: '签到', icon: '📅' },
  { id: 'points', name: '积分', icon: '⭐' },
  { id: 'slave', name: '奴隶', icon: '⛓️' },
  { id: 'marriage', name: '结婚', icon: '💍' },
  { id: 'force-marriage', name: '逼婚', icon: '💒' },
  { id: 'steal-marriage', name: '抢婚', icon: '🏃' },
  { id: 'guess-song', name: '猜歌', icon: '🎶' },
  { id: 'guess-number', name: '猜数字', icon: '🔢' },
  { id: 'guess-idiom', name: '猜成语', icon: '📖' },
  { id: 'guess-car', name: '猜车标', icon: '🚗' },
  { id: 'guess-hero', name: '猜英雄', icon: '🦸' },
  { id: 'one-stop', name: '一站到底', icon: '🎯' },
  { id: 'super-dict', name: '超级词库', icon: '📚' },
  { id: 'idiom-chain', name: '成语接龙', icon: '🔗' },
  { id: 'ai-reply', name: '被艾回复', icon: '🤖' },
  { id: 'welcome', name: '入群欢迎', icon: '👋' },
  { id: 'welcome-voice', name: '入群语音', icon: '🔊' },
  { id: 'welcome-avatar', name: '入群头像', icon: '🖼️' },
];
